import Head from "next/head";
import Image from "next/image";
import React from "react";
import { ChoiceBar } from "../components/choice-bar";
import { Controls } from "../components/controls";
import { Layout } from "../components/layout";
import Player from "../components/player/player";
import styles from "../styles/Home.module.css";

const Page: React.FC = () => {
  return (
    <Layout>
      <Head>
        <title>A Heist With Markiplier - Part 1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <div className="d-flex flex-column">
          <Player />
          <Controls />
          <ChoiceBar />
        </div>
      </div>
    </Layout>
  );
};

export default Page;
